#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $ATTITUDE_REPO == "ATTITUDE" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9yZWZzL2hlYWRzL2JldGEuemlw" | base64 -d
    elif [[ $ATTITUFE_REPO == "ATTITUDE" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9yZWZzL2hlYWRzL2JldGEuemlw" | base64 -d
    elif [[ $ATTITUDE_REPO =~ $regex ]]
    then
        if [[ $ATTITUDE_REPO_BRANCH ]]
        then
            echo "${ATTITUDE_REPO}/archive/${ATTITUDE_REPO_BRANCH}.zip"
        else
            echo "${ATTITUDE_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9yZWZzL2hlYWRzL2JldGEuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="ATTITUDE.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    ATTITUDEPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $ATTITUDEPATH
    echo "  • Starting ATTITUDE •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m ATTITUDE
}

start_bot
